"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const form_1 = require("./form");
exports.form = form_1.form;
const transport_1 = require("./transport");
exports.transport = transport_1.transport;
const log_1 = require("./log");
exports.log = log_1.log;
const logger_1 = require("./logger");
exports.Logger = logger_1.Logger;
const logs_1 = require("./logs");
exports.trace = logs_1.trace;
exports.debug = logs_1.debug;
exports.error = logs_1.error;
exports.fatal = logs_1.fatal;
exports.info = logs_1.info;
exports.warn = logs_1.warn;
